# Generated by Django 5.1.1 on 2025-02-01 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
